typography_spectrum: 0.5086478388402611
color:
  brandStrength: 0.9861207730136812
  lightness: 0.7844077765475959
  saturation: 0.8826822498813272
  rhythmicContrast: 0.8491286812350154
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
layout_spectrum: 0.9831583010964096
author:
  name: Jennifer Vincent
  email: community@coworkpenticton.com
name: Cowork Penticton's work & play blog
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/a278744a-f3b6-4d8a-b3d9-9a6cf4f81e5c.jpg
title: Cowork Penticton's Work & Play Blog
description: You're busy. Here's a curated feed of great stuff.
